<?php
$postData = $data["postData"];
?>

  
    
					
      
      <div id="getInvolved" class="container-fluid">
				<div class="container">
					<h2 class="lineBehindTitle"><span>Get Involved</span></h2>
          <div class="row" id="grid-row">  <!--  ROW 2 OF THE GRIP ON THE PAGE  -->
            <div class="col-sm-12 no-space">
              <div class="grid bg-lightblue">
                <div class="grid-text-container" id="resume-btn-div">
									
									<h1 class="text-center">
										<a>Official Home Page Of SNL Chat</a>
									</h1>
									<h2>
										<a>use menu on top right</a>
									</h2>
                  <h3 class="btn-clear text-center"><a href="/snlchat/public/CrtlLogin">Please Register Now </h3></a> <!-- thisi s the arrow to the right-->
									
                </div>
              </div>
            </div>
           
		      </div>
				</div>
          
      </div>
      <div id="shows" class="container-fluid">
          <div class="container">
            <h1 id="showsHeader">Shows</h1>
          </div>
          <div id="myCarousel" class="carousel slide text-center" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
          </ol>

          <!-- Wrapper for slides THIS WILL BE GENERATED BY PHP CONTROL PANEL-->
          <div class="carousel-inner" role="listbox">
            <div class="item active">
            <h4>"This company is the best. I am so happy with the result!"<br><span style="font-style:normal;">Jose Sebastian Manunta</span></h4>
            </div>
            <div class="item">
              <h4>"One word... WOW!!"<br><span style="font-style:normal;">Jose Sebastian Manunta</span></h4>
            </div>
            <div class="item">
              <h4>"Could I... BE any more happy with this company?"<br><span style="font-style:normal;">Jose Sebastian Manunta</span></h4>
            </div>
          </div>

          <!-- Left and right controls -->
          <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
        <div class="container text-right">
          <a href="#" class="btn btn-primary">View All</a>
        </div>
      </div>
      <div id="extrasSection" class="container-fluid">
        <div class="container"><!-- this will be handled by php code through the control panel-->
          <div class="row"> 
            
            <div class="col-md-4">
              <div class="col-md-12 extrasContainer">
                
                <div class="row"><!-- this will be handled by php code through the control panel-->
                 <h1 class="extrasHeading">Events</h1>
                </div>
                
                <img class="img-responsive" src="/snlchat/app/views/public/images/papi1.jpg"/>
                <h1 class="featuredCategory">Buffalo<!-- category-->
                  <h2 class="featuredTitle">Called to communion</h2> <!-- show title -->
                  <p class="featuredDescription"> <!--deswcription-->
                    What’s stopping you from becoming a Catholic? Join Catholic catechist, writer and speaker, Dr. David Anders, as he explains the Faith to non-Catholics, and addresses their questions and concerns in a kind and compassionate way.
                  </p>
              </div>

            </div>
              <div class="col-md-4 ">
                <div class="col-md-12 extrasContainer">
                  <div class="row"><!-- this will be handled by php code through the control panel-->
                   <h1 class="extrasHeading"><a href="/snlchat/public/ctrlPublic/loadPage/calendar">Calendar</a></h1>
                  </div>  
                  <img class="img-responsive" src="/snlchat/app/views/public/images/papi1.jpg"/>
                  <h1 class="featuredCategory">Buffalo<!-- category-->
                    <h2 class="featuredTitle">Called to communion</h2> <!-- show title -->
                    <p class="featuredDescription"> <!--deswcription-->
                      What’s stopping you from becoming a Catholic? Join Catholic catechist, writer and speaker, Dr. David Anders, as he explains the Faith to non-Catholics, and addresses their questions and concerns in a kind and compassionate way.
                    </p>
              </div>
            </div>
                
          </div>
        </div>
      </div>

